{"body": "You have a different error this time which either means you\u2019ve either made\nprogress and have a new problem or you have more clues to diagnose your\noriginal problem.\n\n\nPreviously the you had:\n\u00a0... | rtcontrib -w -ffc -c -n 2 \\\n\u00a0\u00a0\u00a0 \u00a0\u00a0\u00a0 \u00a0\u00a0\u00a0 -f pool_coords.cal -o %s_caustics.pic \\ ...\nAnd the error was:   rtrace: fatal - command line error at '2'\n\n\nSo you deleted \u2013n 2\n...| rtcontrib -w -ffc -c \\\n\u00a0\u00a0\u00a0 \u00a0\u00a0\u00a0 \u00a0\u00a0\u00a0 -f pool_coords.cal -o %s_caustics.pic \\ ...\n\n\nAnd got the error:  rtrace: fatal - command line error at 'pool_coords.cal'\n\n\nIn both cases the error occurs after the \u2013c option.  I think radiance\nexpects \u2013c to be followed by an argument, which it is taking to be \u2013n in the\nfirst case and \u2013f in the second case.  The following argument (2 or\npool_coords.cal) is then interpreted as an option that doesn\u2019t exist.\n\n\nTry putting a \u20181\u2019 after \u2013c :\n...| rtcontrib -w -ffc -c 1 \\\n\u00a0\u00a0\u00a0 \u00a0\u00a0\u00a0 \u00a0\u00a0\u00a0 -f pool_coords.cal -o %s_caustics.pic \\ ...\n\n\nAnd see what you get.\n\n\n\n\n-Andy\n___\n<sup>Automatically generated content from [radiance mailing-list](https://radiance-online.org/pipermail/radiance-general/2009-August/006155.html).</sup>", "attachments": [], "created_by_name": "Andy McNeil", "created_at": "August 03, 2009 at 08:39AM", "created_by": "Andy_McNeil", "parent_id": "radiance-general_006141", "id": "radiance-general_006155"}